### ISSUE TITLE
Mailing list 

### ISSUE THREAD

**Issue by erinjasinski** [chicagopython/chipy.org#138]
Hi, 

I noticed that when I visit this page to reset my mailing list password ("Password Reminder"), the auto-generated email emails the actual password.  I thought that this was a no-no. I know that this is maintained by python.org, but is there a setting in the ChiPy mailing list to enable hashed passwords only? 

https://mail.python.org/mailman/options/chicago

**Comment by emperorcezar** [comment]
It is not uncommon to email a auto-generated reset password with the
understanding that you'll be changing it as soon as you can. Typically
these days a link is sent with a token, but for all intents and purposes,
that token is a password for the purpose of resetting.

When you say hashed, I think you may mistake that the password is sent in
the email to it being hashed in the db. The password is generated and sent,
then stored in a hashed form in the db. Otherwise it would have sent you
your old password.

-------------------------------------------------------------------------------------------------------------
Father, Pythonista, Cyclist, Brewer. Dabbling in Clojure and Functional
Languages

**Comment by agfor** [comment]
@emperorcezar I think Mailman actually stores passwords in plaintext / reversibly encrypted -- as it has a feature where it can send you your password periodically as a reminder.

**Comment by emperorcezar** [comment]
@agfor that is unfortunate.

**Comment by erinjasinski** [comment]
@agfor  Ah...it is unfortunate.   Thanks for the info!
