### ISSUE TITLE
link orphaned pages

### ISSUE THREAD

**Issue by brianray** [chicagopython/chipy.org#145]
to do:

 - [x] find orphaned pages
 - [x] shared with the chipy organizers
 - [ ]  remove orphaned pages *marked for delete*
 - [ ]  link to home page, pages *approved*

**Comment by JoeJasinski** [comment]
All, 

I've identified the flatpages below and added notes regarding pages that I know about.  Note: in the new design proposal and updated nav, some of these pages are intended to be brought forward. 

- /pages/about/	About Chipy:
  - linked to on main nav
- /pages/conduct/	ChiPy Code of Conduct:
  - linked to in footer
- /pages/organizers/	Current ChiPy Organizers: 
  - linked to in footer
- /pages/organizers/notes/	ChiPy Organizers Notes: 
  - linked to on organizers page
- /pages/referrals/	Referrals
- /pages/SIGs/	Special interest groups: 
  - linked to on homepage banner
- /pages/sigs/finance/	Python in Finance: 
  - not sure where/if this is linked; empty page
- /pages/sigs/mentorship/	ChiPy Python Mentorship: 
  - not sure where/if this is linked
- /pages/sigs/mentorship-process/application/	Mentorship Application Process
  - should this be removed? 
- /pages/sigs/mentorship-tips/mentors/	Mentor Tips
  - should this be removed? 
- /pages/sigs/scientific/	Scientific Computing with Python
  - not sure where/if this is linked; empty
- /pages/sigs/webdev/	Web Programming with Python
  - not sure where/if this is linked; empty
- /pages/sponsor/	Sponsoring Chipy
  - not sure where/if linked. 
- /pages/tshirts/	ChiPy T-Shirts
  - may not be needed anymore since contest is over
- /pages/venue/requirements/	Meeting Venue Requirements
  - not sure where/if this is linked

**Comment by brianray** [comment]
thanks @JoeJasinski Let me know if I can share this with the organizer's list or if you wan to?

**Comment by raymondberg** [comment]
Mentorship stuff has been removed, except for main page which refers to new site.
