### ISSUE TITLE
Add meeting titles

### ISSUE THREAD

**Issue by ZaxR** [chicagopython/chipy.org#218]
Right now the only way to get a custom title for meeting is to make a new "meeting type". As a result, for the one-off jobs event, I had to create a whole meeting type just to add a title to my post. It would be nice if meeting type gave a default title, but if no meeting type was selected, there was an editable title field.

**Comment by sophm256** [comment]
I have submitted a pull request for this. The changes allows one to have a custom meeting title in lieu of showing the 'meeting-type'. That is as Zax suggested.

It does not show a meeting title as Joe Jasinki specified in issue #174 , which is in the form of `<meeting_type>: <meeting_title>` . I do make changes in all the places Joe specifies in the admin and throughout the pages. I don't implement his 2nd to last point, which is:

`The title should be made visible in the meeting dropdown on the Speaker submit page. (note: see the str / unicode method on the Model)`

This is because originally no meeting_type was displayed at all in the 'meeting' dropdown menu on the Speaker submit page.

Also, I have left out the instructions below (from my commit in my pull request) which I'm guessing should go somewhere in the readme.

`
For the ability to have custom meeting titles for meetings, do the following:
-Log into the admin site
-Under 'Meeting types', create a new meeting type by clicking on '+'
-Enter the words 'Meeting-Title' in the 'name' field. Leave the other fields blank and save.
`

1. Please let me know if I should still implement Joe's point that I talked about above. 

2. How should I incorporate the instructions for people that fork the repo in the future? Should I make changes to the readme? If they don't follow the instructions, they won't be able to have custom meeting titles.
