### ISSUE TITLE
Development Environmnet for Windows other than 10 Pro

### ISSUE THREAD

**Issue by elmq0022** [chicagopython/chipy.org#244]
Docker is not compatible with any version of Windows save Windows 10 Pro.  To ensure all members of the Chipy community can contribute to Chipy.org, we should provide instructions to setup a Linux virtual environment on windows.  

For that reason, I propose that we provide instructions to install Vagrant and an Ubuntu box for local development on windows.  Instructions should be added to the README file.

**Comment by elmq0022** [comment]
Docker toolbox does provide the tools necessary to use docker on most windows machines.  We will have to provide some additional information for our setup.  Two main issues:

1. Windows and git tends to change LF line endings to CRLF.  This causes the Linux container to crash on startup with an uninformative error message.  Likely can be addressed with a local gitattributes file specifying line endings as LF.  
2. Browsing to the dev site is less intuitive with this setup.  This can be fixed by forwarding the vm up port 8000 to the host port 8000.  

There are still details to address, but this should be enough for a first solid pull request for testing.

**Comment by sophm256** [comment]
This is going to be a long write up, because I wanted it to be detailed enough in case you want to reproduce any of the setups.

According to link you sent me, https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings , the .gitattributes file overrides an individual's core.autocrlf settings.

### Testing What Happens When You Have a .gitattributes File

**SET UP 1**

I forked the repo after the most recent deployment. I created a branch and added a .gitattribute:

```
* text eol=lf

*.png binary
*.jpg binary
*.jpeg binary
*.tiff binary
*.pdf binary
*.mp3 binary
*.wav binary
```
The git config global setting on my Windows os were: `core.autocrlf=auto`

After cloning this branch to my computer, the files were LF, which is good. But then  `git status` said 4 files were modified (when I had not modified any files):
    
```  
    modified:   chipy_org/static/css/zocial-regular-webfont.eot
    modified:   chipy_org/static/css/zocial-regular-webfont.ttf
    modified:   chipy_org/static/css/zocial-regular-webfont.woff
    modified:   chipy_org/static/js/jquery.js 

```
.............................................................................

**SET UP TWO**

I changed the `.gitattribute` and set .eot,.tff, and .woff extensions to be treated as binary. So now the `.gitattribute` looks like:

```
* text eol=lf

*.png binary
*.jpg binary
*.jpeg binary
*.tiff binary
*.pdf binary
*.mp3 binary
*.wav binary
*.eot binary
*.ttf binary
*.woff binary
```

I did not do anything for the `jquery.js` file, because this file should be treated as a text file and thus be LF EOL.

I made a new directory called ‘setup2’ and cloned into that directory. This time `git status` said only one file was modified: `chipy_org/static/js/jquery.js` I thought what was so special about that file? 

........................................................................

**SET UP 3**

To investigate, I made another setup. I cloned the master branch of the original chipy repo, which doesn't have a .gitattribute .

The files were CRLF, which was to be expected, because I had `core.autocrlf=auto` on a Windows OS. The `chipy_org/static/js/jquery.js` file though was LF EOL. Now that's really puzzling, because why would an LF file in these settings show up as modified in our earlier setup (setup 1 and setup 2), where I have a .gitattribute that explicitly forces files to be LF. 

At this point, I don't know what to do about that jquery.js file.

.................................................................................................................

### Testing What Happens When You Add a New File with CRLF EOL


**SET UP 4**
I wanted to see what happens if you add a new file with a CRLF. Would the CRLF be converted to LF due to the .gitattributes (after you clone it)?

In the folder 'setup2', I add a `test.txt` file with a CRLF EOL. I made a commit to the branch. Then I pushed to my forked repo. I made a new folder `setup4` and pulled that branch. The Git config global settings on my computer are still `core.autocrlf=auto`

I expected the `test.txt` in ‘setup4` to have LF EOL, because of the .gitattributes we defined. Instead, `test.txt` had CRLF EOL. Why hadn't the .gitattributes worked? I have a suspect that the .gitattributes only works for files during the first pull and not for files added afterwards. 

(This link talks about the.gitattribute not working: https://stackoverflow.com/questions/39995131/gitattributes-dont-work-properly-on-mac-and-windows . It says the .gitattribute has to be present during the first commit for it to work. This is not our situation, but it can give us hints to what's going on.)

...........................
**SET UP 5**

I thought about taking a different approach. I thought, why don't I create a new branch from master and set `.gitattributes` to be the following (this set up is from https://git-scm.com/docs/gitattributes):

```
[core]
	autocrlf = input
```

My git global config on my computer is still set to `core.autocrlf=auto`. I got an error message from git when I cloned the branch to a new folder.  This setup did not work and all the cloned files were CRLF. I had copy pasted this setting directly from the link above (which is the official doc). 

Then I changed the .gitattribute, taking out the spaces before and after the ‘=’ sign:
```
[core]
	autocrlf=input
```

This time, there was no error message when I cloned it to a different folder. But the .gitattribute didn't work because the cloned files were CRLF.

...................................

**SET UP 6**

I thought, well the core.autocrlf has to to do with what happens in the working directory. So this time, I made changes to my computer. 

I did `git config --global core.autocrlf "input"` to change configurations on my computer. Then I made a new folder and downloaded the branch (that I'd made in setup2 that had the .gitattributes). I created a new `test.txt` with CRLF, committed it. Then I pushed it to my repo. I downloaded that branch back to a different new folder. I took a look at `test.txt` but it was still CRLF.  So changing the global config settings didn't work. 

Then I added `git config --global core.eol lf`. This didn't help either.

......................

### Conclusion

-Adding .gitattributes will override settings git global settings of core.autocrlf (This is what we want because we want to override a Window OS user setting of `core.autocrlf=auto`)

**Caveats:**
-If a user commits a binary file to the repo, changes have to be made to the .gittatribute.  `*.your-file-extension binary` has to be appended. (But I’m not sure how this is going to pan out considering that the .gitattributes don’t work for new files added when they had line endings of CRLF.)

-If a user adds a new file with a CRLF EOL (where .gitattribute was defined for the project), changing the global config settings on the OS will not work. That is, doing 
 ```
 git config --global core.autocrlf "input"
 git config --global core.eol lf
 ```
will not turn the new file into a LF EOL later after you pushing it to and then cloning it from the repo.

I'm guessing the solution to this would to manually change each new file you create in the text editor to LF before you commit to the repo.

- Also, the `chipy_org/static/js/jquery.js` has to be fixed somehow because it's showing up as modified. What would you suggest I do? Should it commit as is? Or should I somehow try to normalize it? 

```
$ git add --renormalize chipy_org/static/js/jquery.js

$ git commit -m "Normalize all the line endings"
```

https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings at the bottom section shows you how to normalize all of the files, but in our case I think only one file needs to be normalized. The only problem with normalization is that it might cause merge conflicts in some cases: https://www.edwardthomson.com/blog/advent_day_21_renormalizing_line_endings.html

**Comment by sophm256** [comment]
###  Port Forwarding Issues

I got the project to run in Docker on Windows 10 after I had added the `.gitattributes` file. But I was not able to get port forwarding set up like in the link I had sent you: https://stackoverflow.com/questions/42866013/docker-toolbox-localhost-not-working (Second answer) . This is because when I open VirtualBox, no machine shows up!

![virtual-machine-empty](https://user-images.githubusercontent.com/53249319/72830514-8251d600-3c46-11ea-8fe7-5d4cb9f8fb98.JPG)


 I click on the "globaltools" tab, which is located on the upper right corner in that picture. And a host-only ethernet adapter shows up. There's no port forwarding options. Plus, from this window, you can't make a NAT adapter.

![virtual-box-network](https://user-images.githubusercontent.com/53249319/72830737-fd1af100-3c46-11ea-8880-4bb030a51f75.JPG)


When clicked on File > Preferences > Network , I get the windows below.  I can add a NAT Adapter with port forwarding options.

![network](https://user-images.githubusercontent.com/53249319/72830774-10c65780-3c47-11ea-9481-2c64b031b814.JPG)

The problem is, (1) it will not allow me to leave 'Guest IP' blank, (2) I don't think this adapter is associated with a particular VM--but I'm willing to give it a shot to see if it works.

![port-forward](https://user-images.githubusercontent.com/53249319/72830798-1d4ab000-3c47-11ea-9d27-376c0b5becc9.JPG)

Well, it doesn't work.  Then I think perhaps I can open a network connection to VirtualBox from typing within Docker's commandline. I found these links:

https://superuser.com/questions/901422/virtualbox-command-line-setting-up-port-forwarding

https://www.virtualbox.org/manual/ch06.html#natforward

The general form is: 
`VBoxManage controlvm "VM name" --natpf1 "guestssh,tcp,,2222,,22"`

I run the command within Docker's commandline:
`VBoxManage controlvm "default" --natpf1 "myguest-connection,tcp,,8000,,8000"` (note: I'm not sure if this is the right way to run the command not sure about 'myguest-connection')

A error message says it doesn't recognize VBoxManage as a command.

### Conclusion:
I am not able to get port forwarding because the Docker VM doesn't show up in VirtualBox. I installed Docker Toolbox as a one click install that installs VirtualBox, Kitematic, and Docker at the same time. Did you install your DockerToolbox a different way? Was VirtualBox on your computer already before you installed Docker toolbox (so that you didn't have to reinstall it) and hence it might account for a different configuration?

**Comment by elmq0022** [comment]
I like the approach for using the .gitattributes file, but let's be explicit and call out which files are text instead of which files are binary.  That should be safer.  Off the top of my head, text files should be something like:

1.  *.py
1.  *.sh
1.  *.env
1.  *.css
1.  *.yml
1.  *.js
1.  *.txt
1.  *.md
1.  *.html
1.  Dockerfile

I believe I did the same install as you.  No virtual box installed to start.  I have a box labeled default installed.  I did the following:  

Select VM -> settings -> newtork -> advanced -> port forwarding -> add -> 8000 : 8000

![image](https://user-images.githubusercontent.com/3450848/72857811-5e14ea00-3c84-11ea-9288-12109ce50f1c.png)

![image](https://user-images.githubusercontent.com/3450848/72857852-797ff500-3c84-11ea-8711-7821d574eaa9.png)

This let's me browse to the site with localhost:8000

![image](https://user-images.githubusercontent.com/3450848/72858013-04f98600-3c85-11ea-80d3-387ce098c612.png)

If you can put some instructions (I'd create a separate md file and reference it from the readme) together and a .gitattributes file with text files called out specifically, I'll test it out.  

Keep up the good work 😎

**Comment by elmq0022** [comment]
@sophm256 

Just a little more context.  

I wouldn't worry to much about the merge conflicts you mention above.  We'll get the .gitatributes working from our linux / osx machines that use the LF ending and then test the new branch on Windows.  I'm thinking having the .gitatributes file there should prevent the wrong line endings in the first place.  

Also, editing files on the windows machine like you have should be okay.  I'm thinking git will change the ending **on commit** if we have .gitattributes file setup correctly and prevent merge conflicts due to line endings.  

The files in static are "special"  look into the ./manage.py collectstatic command for more info on that when you have time.  Basically, files in static are content that we want nginx (or similar) to serve directly.  Templates need to run though python first to be "rendered".  Images, javascript, css, etc.  do not need to be rendered, just served.

**Comment by elmq0022** [comment]
Push a test branch with a good .gitattributes file, and I'll test it.  Then we can worry about writing instructions.  Sound good?

**Comment by sophm256** [comment]
@elmq0022 , I agree with your approach. I'll create a .gitattribute as you've mentioned above.

>The files in static are "special" look into the ./manage.py collectstatic command for more info on that when you have time.

Yes, I'm familiar with collectstatic. So jquery.js being in that folder would have something to do the anomaly I saw happening ? 

> Push a test branch with a good .gitattributes file, and I'll test it. Then we can worry about writing instructions.

Ok, I'll put together a test branch and send it as a pull request. I know we don't have to worry about writing instructions at this point, but what type of instructions would be needed in the future?

Also, I'm thinking of installing and reinstalling my Docker Toolbox. Could you do me a favor and give me the name of the Docker Toolbox file that you installed, as well a SHA256 hash of the file, so I can compare? Also what Windows version are you running?

Thanks for your help and thanks for the port forwarding instructions. Nice job on getting everything working!  And for also suggesting .gitattributes, instead of dos2unix .  Good teamwork :)

**Comment by sophm256** [comment]
@elmq0022 I just realized something. I'm using a Windows standard account when I'm running Docker and when I was accessing VirtualBox. I went to my Windows Admin account and opened up VirtualBox, I found the Docker machine so it's all good! You don't need to send me the name of the Docker Toolbox file or the hash. I don't think I wouldn't have made this mistake if I was just installing a VM from scratch :)

**Comment by sophm256** [comment]
I've submitted a draft pull request with a `.gitattributes` file that you can look over and test. I gave maintainers the ability to edit this code.

There were some issues. I went back and looked over `setup1`, which I had talked about in an earlier message. It turns out that there were some CRLF files in there, such as 'settings.py',  `chipy-or/apps/__init__.py` and  `chipy_py/static/icons/meeting-logo.svg`   . So in effect, that `.gitattributes` didn't work.

In this new `.gitattributes`, as I've defined in the pull request, there are issues too. I tested it with my computer settings of `core.autocrlf "auto"` .  When cloned from the repo, the file 'settings.py' is LF, which is good. But there are lots of files that are CRLF, such as `chipy-or/apps/__init__.py` and  `chipy_py/static/icons/meeting-logo.svg` . So essentially, this `.gitattributes` doesn't work either.

(Note: Even though .svg files represent images, they are xml text files that can be edited in a text editor, which is why I defined a rule for them in the .gitattributes .)

On a good note, I got port forwarding to work and the site shows up on my browser. Please let me know how testing goes regarding the `.gitattributes` . Thanks!

**Comment by nick-symon** [comment]
**Using Chocolatey to install Make**
Windows does not have make automatically installed, so we recommend using the package manage chocolatey to install make.

**Step 1. Install Chocolatey**
Follow the instructions at https://chocolatey.org/install to install chocolatey. Please make sure that you open powershell as administrator when following the instructions.

**Step 2. Install make**
Once chocolatey is installed, run the following command in powershell (as administrator):
`choco install make` 

Now you will have make installed (including in the docker quickstart terminal) and will be able to follow along with the set up instructions!

**Comment by elmq0022** [comment]
#247 closes this issue.  Thanks @sophm256 for putting this together. Great work on this one.  Thanks to @nick-symon for testing the windows solution and suggesting Chocolatey for installing "gnu make" on windows.
