### ISSUE TITLE
ChiPy Announcement Dialog in the admin is not editable

### ISSUE THREAD

**Issue by JoeJasinski** [chicagopython/chipy.org#264]
On the announcement detail page, the announcement "Text" field is grayed out. 

https://www.chipy.org/admin/announcements/announcement/58/change/

![image](https://user-images.githubusercontent.com/417872/76368382-1282d200-62fe-11ea-959e-7fad17543a44.png)

**Comment by elmq0022** [comment]
Thanks Joe.  I will look into it as soon as I can.

**Comment by elmq0022** [comment]
@JoeJasinski  I took a look my local dev with the deployed code.  and a deploy to heroku.  Both work just fine. This unfortunately makes it hard for me to know where to start to fix the issue.    

![screen](https://user-images.githubusercontent.com/3450848/76374773-1f112580-6312-11ea-96cd-fbc1d2014039.png)
@raymondberg my credentials don't give me access to announcements on the live site.  Could you verify @JoeJasinski 's issue.  Could you try refreshing the cache if it doesn't?  

On a separate note, we have two "rich" text editor on the site.  How would you guys feel about ditching one of them?  The one that's causing problems right now is ckeditor.  The other is tinymce (sp?).  

Could we swap the ckeditor for tinymce? 

Thanks!

**Comment by elmq0022** [comment]
@JoeJasinski I see you did get an announcement up today.  Were you able to get it to work through the admin, or did you need to use a some backdoor?  

I also see the prior announcement was posted December 16th, which is actually several deploys back.  I'll see if I can go back to a previous deploy and find where it broke.  It might be easier to try deploying an update version though and seeing if that resolves it.

**Comment by sophm256** [comment]
@elmq0022 I'm just going to throw out some ideas which might or might not work. 

idea 1) do a collectstatic in production  

https://stackoverflow.com/questions/57089999/ckeditor-in-django-not-working-in-production 

https://stackoverflow.com/questions/49020840/django-2-0-1-with-ckeditor-doesnt-work-on-admin-page/54272536#54272536

idea 2) That second link has an answer for django 2, while I know we've upgraded to django 3. The first and most upvoted answer has to do with specifying a path to find the editor in a static directory. We currently don't have this defined in our settings.

idea 3) Two of the answers in 2nd link have to do with static files. Maybe S3 settings are not optimal?

idea 4) Install ckeditor without extra 3rd party plugins and work from there. The 2 links are solutions for the toolbar being greyed out, whereas we have the problem of them not showing up. But it may be worth a shot.
https://ckeditor.com/old/forums/CKEditor/All-the-toolbar-buttons-are-disabledGreyed-out...please-help
https://ckeditor.com/old/forums/CKEditor/When-loadingrefresh-the-CKEditor-page-the-toolbar-gets-greyed-out-sporadic-with-the

**Comment by sophm256** [comment]
@elmq0022 On Slack you said you tested it on your machine and it works. (I haven't tested it.) But along the lines of idea 3, maybe the reason the ckeditor doesn't show up is because the deployed site doesn't have upgraded django-storages and boto3.  

I've posted this link before in the above comment. The second answer in that link says "server can't find the static files needed to render ckeditor's widgets".
https://stackoverflow.com/questions/49020840/django-2-0-1-with-ckeditor-doesnt-work-on-admin-page/54272536#54272536

So without those upgrades from your pull request, maybe the ckeditor widgets won't show up.

**Comment by elmq0022** [comment]
@sophm256, I appreciate the thought on all these. I think I'm just going to upgrade the package first and see if that straightens stuff out.  

I'd like to take a closer look in prod and try to debug that way, but I don't access to this section of the admin :frowning_face: 

Since have not been able to replicate the error, it's going to be terribly difficult to diagnosis.

**Comment by elmq0022** [comment]
Looks like version 5.9.0 is tested against django 1.11.x and python 3.6.x

https://github.com/django-ckeditor/django-ckeditor/blob/5.9.0/tox.ini

So, let's roll with that.

**Comment by elmq0022** [comment]
This was fixed with #265

**Comment by JoeJasinski** [comment]
Thank you @elmq0022 - look good.

**Comment by elmq0022** [comment]
Thanks Joe.  I'm glad it works for you.
