### ISSUE TITLE
captcha broken on contact form

### ISSUE THREAD

**Issue by brianray** [chicagopython/chipy.org#88]
![ss](https://cloud.githubusercontent.com/assets/676284/6380921/62b12e1e-bd0b-11e4-9568-7197345b7547.jpg)

**Comment by brianray** [comment]
Also, is there a way to add "chicago-organizers@python.org" <chicago-organizers@python.org> to the list of ppl who get these?

**Comment by emperorcezar** [comment]
@JoeJasinski you upgraded the captcha library, could you take a look at this?

**Comment by JoeJasinski** [comment]
@emperorcezar, @brianray  Glad to have help,

Was the recaptcha site key and secret key set as environment variables?  

    export NORECAPTCHA_SITE_KEY=your_recaptcha_public_key
    export NORECAPTCHA_SECRET_KEY=your_recaptcha_private_key

Due to the Recaptcha 2.0 api upgrade, I'm not sure if the old recaptcha keys will work and they might need to be regenerated.  This can be done in the google dashboard.  I assume chipy has a Recaptcha account for this already, or I can generate the keys and send them to you. 

    https://www.google.com/recaptcha/admin#list

**Comment by emperorcezar** [comment]
All fixed.

**Comment by JoeJasinski** [comment]
Great!

**Comment by brianray** [comment]
Thank you guys. But I just tested. I do see the captcha; however, an email is never submitted.

**Comment by brianray** [comment]
Ah, got the email now. I will open a new ticket for adding  "chicago-organizers@python.org"
